learning_templates/basic_app/urls.py
from basic_app import views
from django.urls import path

#Template tagging

app_name='basic_app'

#aca especifico adonde redirigir cuando es llamado desde la pagina de la 
# forma 127.0.0.1:8000/other o lo q sea 
urlpatterns=[
    path('',views.index,name='index'),
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
#importamos las views desde la app
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict ={'text':'hola mundo','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relativeurl.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Cuarta app</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     </head>
    <body>

<div class="container">
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Brand</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="#">Admin</a>
        <a class="nav-item nav-link" href="#">Other</a>
      </div>
    </div>
  </nav>
</div>

      <div class="container">

      {% block body_block %}
      <!-- todo esto es heredado si extends  -->
      
      {% endblock  %}

      </div>


    </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>Bienvenido a index</h1>
<h2>Otro ejemplo de herencia de templates en index.html</h2>
<h1>{{ text|upper  }}</h1>
<h1>{{ text|cut:'mundo'  }}</h1>
<h1>{{ number| add:"99" }}</h1>
{% endblock %} 

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}
<h1> Bienvenido a other </h1>
<h2> Ejemplo de herencia de templates </h2>


{% endblock %}

learning_templates/templates/basic_app/relativeurl.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Cuarta app</title>
     </head>
    <body>

        <h1>Bienvenido a xd</h1>
        <a href="{% url 'basic_app:other' %}">La other page</a>
        <a href="{% url 'admin:index' %}">Admin</a>
        <a href="{% url 'basic_app:index' %}">Index</a>


       
    </br>
        
    </body>
</html>